FROM python:3.11.3-slim-buster

COPY ../requirements.txt    ./app/requirements.txt
COPY ../src/wb_data_service ./app/wb_data_service
COPY ../src/wb_data_shared  ./app/wb_data_shared

RUN apt-get update && apt-get install
RUN pip install -r ./app/requirements.txt

ENV PYTHONPATH=./app

EXPOSE 8000

CMD ["python", "-O", "./app/wb_data_service/main.py"]
