FROM python:3.11.3-slim-buster

COPY ../requirements.txt    ./app/requirements.txt
COPY ../src/wb_data_tg_bot ./app/wb_data_tg_bot
COPY ../src/wb_data_shared  ./app/wb_data_shared

RUN apt-get update && apt-get install
RUN pip install -r ./app/requirements.txt

ENV PYTHONPATH=./app

EXPOSE 8005

CMD ["python", "-O", "./app/wb_data_tg_bot/main.py"]
